### ISSUE TITLE
Create step by step guide

### ISSUE THREAD

**Issue by Justin417** [Oflameo/pittmesh_dns#1]
I suggest we do a quick write-up on step by step instructions on how to install this application on linux systems, so that users who have never used ansible can get this up and running quickly. 

John, if you wouldn't mind sending me some rough instructions, I'd be happy to write up some wiki pages for the project to help others in the future.

**Comment by Oflameo** [comment]
See ansible docs for setting up [inventory](https://docs.ansible.com/ansible/intro_inventory.html). 

ansible-playbook -e hosts=$host user=$user  basepkg.yml
ansible-playbook -e hosts=$host user=$user  specpkg.yml

**Comment by Oflameo** [comment]
See ansible docs on how to setup [inventory](https://docs.ansible.com/ansible/intro_inventory.html)

`ansible-playbook -e hosts=$hosts user=$user basepkg.yml`
`ansible-playbook -e hosts=$hosts user=$user specpkg.yml`

**Comment by Oflameo** [comment]
See ansible docs on how to setup inventory.

Go into the cloned directory.

`ansible-playbook -e "hosts=$hosts user=$user" basepkg.yml`
`ansible-playbook -e "hosts=$hosts user=$user" specpkg.yml`

**Comment by Oflameo** [comment]
The guide is created.

https://github.com/Oflameo/pittmesh_dns/blob/master/setup.md
